Name:           perl-Tie-FS
Version:        0.1.0
Release:        1%{?dist}
Summary:        Read and write files using a tied hash
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Tie-FS/
Source0:        http://www.cpan.org/modules/by-module/Tie/Tie-FS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module ties a hash to a directory in the filesystem. If no directory
is specified in the $dir parameter, then "." (the current directory) is
assumed. The $flag parameter defaults to the "Create" flag.

%prep
%setup -q -n Tie-FS-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 28 2011 Deven T. Corzine <deven@ties.org> 0.1.0-1
- Specfile autogenerated by cpanspec 1.77.
